/*
 * This file was automatically generated by EvoSuite
 * Wed Jul 31 08:57:58 GMT 2019
 */

package org.owasp.html.examples;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;
import org.owasp.html.HtmlStreamEventReceiver;
import org.owasp.html.examples.UrlTextExample;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, useJEE = true) 
public class UrlTextExample_ESTest extends UrlTextExample_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String[] stringArray0 = new String[2];
      stringArray0[0] = "d8&*h:A<}";
      stringArray0[1] = "d8&*h:A<}";
      UrlTextExample.main(stringArray0);
      String[] stringArray1 = new String[6];
      stringArray1[0] = "P;>_J![h*NA]^<p";
      stringArray1[1] = "d8&*h:A<}";
      stringArray1[2] = "";
      stringArray1[3] = "d8&*h:A<}";
      stringArray1[4] = "d8&*h:A<}";
      stringArray1[5] = "";
      UrlTextExample.main(stringArray1);
      assertNotSame(stringArray1, stringArray0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      HtmlStreamEventReceiver htmlStreamEventReceiver0 = mock(HtmlStreamEventReceiver.class, new ViolatedAssumptionAnswer());
      UrlTextExample.AppendDomainAfterText urlTextExample_AppendDomainAfterText0 = new UrlTextExample.AppendDomainAfterText(htmlStreamEventReceiver0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      UrlTextExample urlTextExample0 = new UrlTextExample();
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      // Undeclared exception!
      try { 
        UrlTextExample.main((String[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      String[] stringArray0 = new String[3];
      // Undeclared exception!
      try { 
        UrlTextExample.main(stringArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.google.common.base.Preconditions", e);
      }
  }
}
